### ISSUE TITLE
Can find branches if the name is not all lower case.

### ISSUE THREAD

**Issue by westi** [Automattic/calypso-live-branches#10]
Trying to boot https://calypso.live/?branch=fix/WCS-stats-undefined-increase fails because of 'Branch not found fix/wcs-stats-undefined-increase'

**Comment by westi** [comment]
Probably caused by: https://github.com/Automattic/calypso-live-branches/blob/d0a56ddb7ee65bd888edc1305558f4ca4fd17357/lib/proxy-middlewares.js#L31

**Comment by Tug** [comment]
Thanks for the report @westi. Fixed in https://github.com/Automattic/calypso-live-branches/commit/09de59779665855b4f2df2dd734c064e73047be0
