### ISSUE TITLE
Add an endpoint/query string to retrieve branch status

### ISSUE THREAD

**Issue by hoverduck** [Automattic/calypso-live-branches#4]
It would be useful for automated tests to have a way to query the current status of a given branch.  i.e. I'd like to hit `https://calypso.live/?branch=BRANCH&status=1` and get back a JSON response like

`{ branch: 'BRANCH', status: 'BOOTING' }`

I'm sure there's plenty of other metadata that could be squeezed in there too, like when the branch was started, or the GitHub commit ID so you can confirm you're running the branch with the latest updates.

**Comment by Tug** [comment]
This has been added in the last version of calypso.live. The default responses are:
- `{ branch: 'BRANCH', status: 'DOWN' }` branch is down
- `{ branch: 'BRANCH', status: 'BOOTING' }` branch is booting (ie running `git checkout` and `npm install`)
- `{ branch: 'BRANCH', status: 'UP' }` branch has booted and is listening to incoming requests

https://github.com/Automattic/wp-calypso/pull/6444 is still needed to really know when calypso is ready (the build has finished).

Once it is merged, we will have access to those additional types of responses:
- `{ branch: 'BRANCH', status: 'ready' }` compiler has finished building the client, the app is ready
- `{ branch: 'BRANCH', status: 'invalid' }` the client sources have been updated and needs recompiling
- `{ branch: 'BRANCH', status: 'compiling' }` compiler is rebuilding the client
