### ISSUE TITLE
502 Gateway error

### ISSUE THREAD

**Issue by Tug** [Automattic/calypso-live-branches#5]
When a branch takes too much time to boot (and the boot page is not displayed) nginx reverse proxy can return a `502 bad gateway` error. Reloading the page at that point usually works.

This should not happen since the booting page is supposed to reload every 5 seconds, but it does happen in practice.

Here are a few possibilities which should be investigated:
- CPU is at 100% (because it's building another branch for instance) and cannot serve the page in time.
- A bug somewhere makes the call to `net.listen()` never return (or `net.listen` is never called in the first place).
  Might be worth investigating issue #2 first

**Comment by nylen** [comment]
I am seeing this issue as well.  It appears to happen when calypso.live thinks the app is done booting, but it has not started accepting connections yet.  As you noted, everything works when reloading the page.

**Comment by Tug** [comment]
It seems this event is never emitted from any worker: https://github.com/Automattic/calypso-live-branches/blob/master/lib/proxy-manager.js#L67
If this happens on a branch which has been updated, it might explain the error.

Edit: it's however emitted from the callback a few lines after, but that supposed there is no error, still worth investigating

**Comment by Tug** [comment]
I haven't encountered this bug in production since then. Closing.
