### ISSUE TITLE
Failed git reset --hard on rebooting

### ISSUE THREAD

**Issue by folletto** [Automattic/calypso-live-branches#8]
I got this error trying to reboot a branch:

> Command failed: git fetch origin; git reset --hard @{u} Auto packing the repository in background for optimum performance. See "git help gc" for manual housekeeping. fatal: Unable to create '/...cut.../data/gh-wp-calypso/branches/fix/double-themes-query/.git/index.lock': File exists. If no other git process is currently running, this probably means a git process crashed in this repository earlier. Make sure no other git process is running and remove the file manually to continue.

**Comment by Tug** [comment]
It seems to be due to concurrent calls to `Branch.prototype.update` (or `git reset --hard @{u}` for the same repo).
We should inspect the logic around here https://github.com/Automattic/calypso-live-branches/blob/master/lib/proxy-manager.js#L100 I believe

**Comment by WalterBoles** [comment]
Well at least we know how’s it is now wright and they won’t be doing that any more and as alway set up payment plan

**Comment by WalterBoles** [comment]
I’m not dead I promise
